create extension if not exists "pgcrypto";

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  role text not null default 'customer' check (role in ('customer', 'admin')),
  full_name text not null default '',
  phone text not null default '',
  state text not null default 'Lagos',
  city text not null default 'Lagos',
  address text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.categories (
  id text primary key,
  name text not null unique,
  count integer not null default 0,
  image text not null default '',
  sort_order integer not null default 0
);

create table if not exists public.products (
  id text primary key,
  name text not null,
  description text not null default '',
  category_id text not null references public.categories(id),
  subcategory text not null default '',
  price numeric(12, 2) not null check (price >= 0),
  compare_at_price numeric(12, 2),
  featured boolean not null default false,
  newest boolean not null default false,
  trending boolean not null default false,
  installment_available boolean not null default false,
  installment_amount numeric(12, 2),
  tags text[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.product_images (
  id bigint generated by default as identity primary key,
  product_id text not null references public.products(id) on delete cascade,
  url text not null,
  sort_order integer not null default 0,
  unique (product_id, sort_order)
);

create table if not exists public.product_variants (
  id bigint generated by default as identity primary key,
  product_id text not null references public.products(id) on delete cascade,
  size text not null default '',
  color text not null default '',
  sku text unique,
  unique (product_id, size, color)
);

create table if not exists public.inventory (
  product_variant_id bigint primary key references public.product_variants(id) on delete cascade,
  quantity integer not null default 0 check (quantity >= 0),
  updated_at timestamptz not null default now()
);

create table if not exists public.wishlists (
  user_id uuid not null references auth.users(id) on delete cascade,
  product_id text not null references public.products(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, product_id)
);

create table if not exists public.carts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.cart_items (
  cart_id uuid not null references public.carts(id) on delete cascade,
  product_variant_id bigint not null references public.product_variants(id),
  quantity integer not null check (quantity > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (cart_id, product_variant_id)
);

create table if not exists public.orders (
  id text primary key,
  user_id uuid not null references auth.users(id) on delete restrict,
  full_name text not null,
  phone text not null,
  email text not null,
  state text not null,
  city text not null,
  address text not null,
  notes text not null default '',
  total numeric(12, 2) not null check (total >= 0),
  paid numeric(12, 2) not null default 0 check (paid >= 0),
  remaining numeric(12, 2) not null default 0 check (remaining >= 0),
  payment_method text not null check (payment_method in ('full', 'installment', 'bank-transfer')),
  status text not null default 'pending' check (status in ('pending', 'payment-verification', 'confirmed', 'processing', 'shipped', 'out-for-delivery', 'delivered', 'cancelled')),
  expected_delivery text not null,
  tracking_code text not null default '',
  courier text not null default '',
  fulfillment_notes text not null default '',
  installment_frequency text check (installment_frequency in ('weekly', 'monthly')),
  next_payment_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id text not null references public.orders(id) on delete cascade,
  product_id text not null references public.products(id),
  product_name text not null,
  image text not null default '',
  quantity integer not null check (quantity > 0),
  unit_price numeric(12, 2) not null check (unit_price >= 0),
  size text not null default '',
  color text not null default ''
);

create table if not exists public.installment_plans (
  id uuid primary key default gen_random_uuid(),
  order_id text not null unique references public.orders(id) on delete cascade,
  frequency text not null check (frequency in ('weekly', 'monthly')),
  total_amount numeric(12, 2) not null check (total_amount >= 0),
  paid_amount numeric(12, 2) not null default 0 check (paid_amount >= 0),
  remaining_amount numeric(12, 2) not null default 0 check (remaining_amount >= 0),
  next_payment_at timestamptz,
  status text not null default 'active' check (status in ('active', 'complete', 'overdue', 'cancelled')),
  created_at timestamptz not null default now()
);

create table if not exists public.installment_payments (
  id uuid primary key default gen_random_uuid(),
  plan_id uuid not null references public.installment_plans(id) on delete cascade,
  amount numeric(12, 2) not null check (amount > 0),
  due_at timestamptz,
  paid_at timestamptz,
  status text not null default 'pending' check (status in ('pending', 'paid', 'rejected')),
  reference text not null default '',
  receipt_path text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.payment_methods (
  id text primary key,
  name text not null,
  enabled boolean not null default true,
  instructions text not null default '',
  sort_order integer not null default 0
);

create table if not exists public.payment_records (
  id uuid primary key default gen_random_uuid(),
  order_id text not null references public.orders(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  method text not null,
  amount numeric(12, 2) not null check (amount > 0),
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  reference text not null default '',
  receipt_path text not null default '',
  notes text not null default '',
  reviewed_by uuid references auth.users(id),
  reviewed_at timestamptz,
  created_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_updated_at on public.profiles;
create trigger profiles_updated_at before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists carts_updated_at on public.carts;
create trigger carts_updated_at before update on public.carts
for each row execute function public.set_updated_at();

drop trigger if exists inventory_updated_at on public.inventory;
create trigger inventory_updated_at before update on public.inventory
for each row execute function public.set_updated_at();

drop trigger if exists products_updated_at on public.products;
create trigger products_updated_at before update on public.products
for each row execute function public.set_updated_at();

drop trigger if exists cart_items_updated_at on public.cart_items;
create trigger cart_items_updated_at before update on public.cart_items
for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name)
  values (
    new.id,
    coalesce(new.email, ''),
    coalesce(new.raw_user_meta_data ->> 'full_name', '')
  )
  on conflict (id) do update set email = excluded.email;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.product_images enable row level security;
alter table public.product_variants enable row level security;
alter table public.inventory enable row level security;
alter table public.wishlists enable row level security;
alter table public.carts enable row level security;
alter table public.cart_items enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.installment_plans enable row level security;
alter table public.installment_payments enable row level security;
alter table public.payment_methods enable row level security;
alter table public.payment_records enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer set search_path = public
as $$
  select exists (select 1 from public.profiles where id = auth.uid() and role = 'admin');
$$;

drop policy if exists "public can read categories" on public.categories;
create policy "public can read categories" on public.categories for select using (true);
drop policy if exists "public can read products" on public.products;
create policy "public can read products" on public.products for select using (true);
drop policy if exists "public can read product images" on public.product_images;
create policy "public can read product images" on public.product_images for select using (true);
drop policy if exists "public can read product variants" on public.product_variants;
create policy "public can read product variants" on public.product_variants for select using (true);
drop policy if exists "public can read inventory" on public.inventory;
create policy "public can read inventory" on public.inventory for select using (true);

drop policy if exists "customers can read their profile" on public.profiles;
create policy "customers can read their profile" on public.profiles for select using (auth.uid() = id);
drop policy if exists "customers can update their profile" on public.profiles;
create policy "customers can update their profile" on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);
drop policy if exists "admins can manage profiles" on public.profiles;
create policy "admins can manage profiles" on public.profiles for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists "customers can read their wishlist" on public.wishlists;
create policy "customers can read their wishlist" on public.wishlists for select using (auth.uid() = user_id);
drop policy if exists "customers can manage their wishlist" on public.wishlists;
create policy "customers can manage their wishlist" on public.wishlists for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "customers can manage their cart" on public.carts;
create policy "customers can manage their cart" on public.carts for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "customers can manage their cart items" on public.cart_items;
create policy "customers can manage their cart items" on public.cart_items
for all using (
  exists (select 1 from public.carts where carts.id = cart_items.cart_id and carts.user_id = auth.uid())
)
with check (
  exists (select 1 from public.carts where carts.id = cart_items.cart_id and carts.user_id = auth.uid())
);

drop policy if exists "customers can read their orders" on public.orders;
create policy "customers can read their orders" on public.orders for select using (auth.uid() = user_id);
drop policy if exists "customers can create their orders" on public.orders;
create policy "customers can create their orders" on public.orders for insert with check (auth.uid() = user_id);
drop policy if exists "customers can read their order items" on public.order_items;
create policy "customers can read their order items" on public.order_items for select using (
  exists (select 1 from public.orders where orders.id = order_items.order_id and orders.user_id = auth.uid())
);
drop policy if exists "customers can create their order items" on public.order_items;
create policy "customers can create their order items" on public.order_items for insert with check (
  exists (select 1 from public.orders where orders.id = order_items.order_id and orders.user_id = auth.uid())
);

drop policy if exists "customers can read their installment plans" on public.installment_plans;
create policy "customers can read their installment plans" on public.installment_plans for select using (
  exists (select 1 from public.orders where orders.id = installment_plans.order_id and orders.user_id = auth.uid())
);
drop policy if exists "customers can read their installment payments" on public.installment_payments;
create policy "customers can read their installment payments" on public.installment_payments for select using (
  exists (
    select 1 from public.installment_plans
    join public.orders on orders.id = installment_plans.order_id
    where installment_plans.id = installment_payments.plan_id and orders.user_id = auth.uid()
  )
);
drop policy if exists "public can read enabled payment methods" on public.payment_methods;
create policy "public can read enabled payment methods" on public.payment_methods for select using (enabled = true);
drop policy if exists "customers can read their payment records" on public.payment_records;
create policy "customers can read their payment records" on public.payment_records for select using (auth.uid() = user_id);
drop policy if exists "customers can create their payment records" on public.payment_records;
create policy "customers can create their payment records" on public.payment_records for insert with check (auth.uid() = user_id);
drop policy if exists "admins can manage products" on public.products;
create policy "admins can manage products" on public.products for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admins can manage product images" on public.product_images;
create policy "admins can manage product images" on public.product_images for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admins can manage product variants" on public.product_variants;
create policy "admins can manage product variants" on public.product_variants for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admins can manage inventory" on public.inventory;
create policy "admins can manage inventory" on public.inventory for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admins can manage orders" on public.orders;
create policy "admins can manage orders" on public.orders for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admins can manage order items" on public.order_items;
create policy "admins can manage order items" on public.order_items for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admins can manage installment plans" on public.installment_plans;
create policy "admins can manage installment plans" on public.installment_plans for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admins can manage installment payments" on public.installment_payments;
create policy "admins can manage installment payments" on public.installment_payments for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admins can manage payment methods" on public.payment_methods;
create policy "admins can manage payment methods" on public.payment_methods for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admins can manage payment records" on public.payment_records;
create policy "admins can manage payment records" on public.payment_records for all using (public.is_admin()) with check (public.is_admin());