import type {
  Category,
  Order,
  OrderItem,
  Product,
} from "@workspace/api-zod";

const image = (id: string) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1200&q=85`;

export const categories: Category[] = [
  {
    id: "new-arrivals",
    name: "New Arrivals",
    count: 24,
    image: image("photo-1483985988355-763728e1935b"),
  },
  {
    id: "women",
    name: "Women",
    count: 42,
    image: image("photo-1496747611176-843222e1e57c"),
  },
  {
    id: "men",
    name: "Men",
    count: 31,
    image: image("photo-1617127365659-c47fa864d8bc"),
  },
  {
    id: "footwear",
    name: "Footwear",
    count: 18,
    image: image("photo-1543163521-1bf539c55dd2"),
  },
  {
    id: "bags",
    name: "Bags",
    count: 16,
    image: image("photo-1584917865442-de89df76afd3"),
  },
  {
    id: "accessories",
    name: "Accessories",
    count: 28,
    image: image("photo-1523779917675-b6ed3a42a561"),
  },
  {
    id: "beauty",
    name: "Beauty",
    count: 12,
    image: image("photo-1596462502278-27bfdc403348"),
  },
  {
    id: "lifestyle",
    name: "Lifestyle",
    count: 20,
    image: image("photo-1524758631624-e2822e304c36"),
  },
];

export const products: Product[] = [
  {
    id: "sahara-sculpted-dress",
    name: "Sahara Sculpted Dress",
    description:
      "A fluid, sculpted silhouette cut in a softly structured crepe. Designed to hold its shape from first entrance to last light.",
    category: "Women",
    subcategory: "Dresses",
    price: 148000,
    compareAtPrice: 175000,
    image: image("photo-1539109136881-3be0616acf4b"),
    images: [
      image("photo-1539109136881-3be0616acf4b"),
      image("photo-1515886657613-9f3515b0c78f"),
      image("photo-1506629905607-d9f297d5a04f"),
    ],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Obsidian", "Clay"],
    stock: 8,
    tags: ["new", "occasion"],
    featured: true,
    newest: true,
    trending: true,
    installmentAvailable: true,
    installmentAmount: 49333,
  },
  {
    id: "lagos-relaxed-shirt",
    name: "Lagos Relaxed Shirt",
    description:
      "An easy everyday layer with an architectural collar and a relaxed cut. Finished in a breathable cotton-linen blend.",
    category: "Men",
    subcategory: "Shirts",
    price: 68000,
    compareAtPrice: null,
    image: image("photo-1596755094514-f87e34085b2c"),
    images: [
      image("photo-1596755094514-f87e34085b2c"),
      image("photo-1610652492500-ded49ceeb378"),
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Ecru", "Midnight"],
    stock: 15,
    tags: ["everyday", "essential"],
    featured: true,
    newest: false,
    trending: true,
    installmentAvailable: false,
    installmentAmount: null,
  },
  {
    id: "studio-leather-tote",
    name: "Studio Leather Tote",
    description:
      "A generous everyday tote in full-grain leather, made for a laptop, a second pair of shoes, and whatever the day asks of you.",
    category: "Bags",
    subcategory: "Totes",
    price: 95000,
    compareAtPrice: 112000,
    image: image("photo-1548036328-c9fa89d128fa"),
    images: [
      image("photo-1548036328-c9fa89d128fa"),
      image("photo-1584917865442-de89df76afd3"),
    ],
    sizes: ["One Size"],
    colors: ["Espresso", "Black"],
    stock: 5,
    tags: ["leather", "work"],
    featured: true,
    newest: true,
    trending: false,
    installmentAvailable: true,
    installmentAmount: 31667,
  },
  {
    id: "bloom-heeled-sandal",
    name: "Bloom Heeled Sandal",
    description:
      "A barely-there sandal with a considered curve and a softly squared toe. Made for late dinners and longer nights.",
    category: "Footwear",
    subcategory: "Heels",
    price: 72000,
    compareAtPrice: null,
    image: image("photo-1543163521-1bf539c55dd2"),
    images: [
      image("photo-1543163521-1bf539c55dd2"),
      image("photo-1560343090-f0409e92791a"),
    ],
    sizes: ["36", "37", "38", "39", "40", "41"],
    colors: ["Bone", "Noir"],
    stock: 11,
    tags: ["occasion", "new"],
    featured: false,
    newest: true,
    trending: true,
    installmentAvailable: false,
    installmentAmount: null,
  },
  {
    id: "linea-mini-hoops",
    name: "Linea Mini Hoops",
    description:
      "Light-catching sculptural hoops with a polished finish. An everyday signature with just enough presence.",
    category: "Jewelry",
    subcategory: "Earrings",
    price: 32000,
    compareAtPrice: null,
    image: image("photo-1535632066927-ab7c9ab60908"),
    images: [image("photo-1535632066927-ab7c9ab60908")],
    sizes: ["One Size"],
    colors: ["Gold", "Silver"],
    stock: 24,
    tags: ["gift", "essential"],
    featured: false,
    newest: false,
    trending: true,
    installmentAvailable: false,
    installmentAmount: null,
  },
  {
    id: "after-hours-overshirt",
    name: "After Hours Overshirt",
    description:
      "A softly tailored overshirt for the space between dressed and undone. Cut to layer over a tee or a fine knit.",
    category: "Men",
    subcategory: "Outerwear",
    price: 118000,
    compareAtPrice: 135000,
    image: image("photo-1551488831-00ddcb6c6bd3"),
    images: [
      image("photo-1551488831-00ddcb6c6bd3"),
      image("photo-1610652492500-ded49ceeb378"),
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Stone", "Olive"],
    stock: 4,
    tags: ["layering", "limited"],
    featured: false,
    newest: true,
    trending: false,
    installmentAvailable: true,
    installmentAmount: 39333,
  },
  {
    id: "muse-fragrance",
    name: "Muse Eau de Parfum",
    description:
      "A warm, skin-close scent built around iris, smoked woods, and a quiet trace of vanilla.",
    category: "Beauty",
    subcategory: "Fragrance",
    price: 55000,
    compareAtPrice: null,
    image: image("photo-1541643600914-78b084683601"),
    images: [image("photo-1541643600914-78b084683601")],
    sizes: ["50ml"],
    colors: ["Original"],
    stock: 19,
    tags: ["signature", "gift"],
    featured: false,
    newest: false,
    trending: true,
    installmentAvailable: false,
    installmentAmount: null,
  },
  {
    id: "forma-wide-trouser",
    name: "Forma Wide Trouser",
    description:
      "A long, elegant line with a high waist and a fluid drape. The pair that makes every top feel intentional.",
    category: "Women",
    subcategory: "Trousers",
    price: 89000,
    compareAtPrice: 104000,
    image: image("photo-1594633312681-425c7b97ccd1"),
    images: [
      image("photo-1594633312681-425c7b97ccd1"),
      image("photo-1515886657613-9f3515b0c78f"),
    ],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Sand"],
    stock: 9,
    tags: ["tailoring", "new"],
    featured: true,
    newest: false,
    trending: false,
    installmentAvailable: false,
    installmentAmount: null,
  },
];

export const makeTimeline = (status: Order["status"]): Order["timeline"] => {
  const stages = [
    "pending",
    "payment-verification",
    "confirmed",
    "processing",
    "shipped",
    "out-for-delivery",
    "delivered",
  ] as const;
  const currentIndex = stages.indexOf(status as (typeof stages)[number]);
  const labels = [
    "Order placed",
    "Payment verification",
    "Order confirmed",
    "Being prepared",
    "Shipped",
    "Out for delivery",
    "Delivered",
  ];

  return labels.map((label, index) => ({
    label,
    date: index <= currentIndex ? "Sep 24, 2026" : null,
    complete: index < currentIndex || status === "delivered",
    current: index === currentIndex,
  }));
};

const orderItems: OrderItem[] = [
  {
    productId: products[0].id,
    productName: products[0].name,
    image: products[0].image,
    quantity: 1,
    unitPrice: products[0].price,
    size: "M",
    color: "Obsidian",
  },
  {
    productId: products[2].id,
    productName: products[2].name,
    image: products[2].image,
    quantity: 1,
    unitPrice: products[2].price,
    size: "One Size",
    color: "Espresso",
  },
];

export const orders: Order[] = [
  {
    id: "JLF-240926-01",
    items: orderItems,
    total: 243000,
    paid: 243000,
    remaining: 0,
    paymentMethod: "full",
    status: "shipped",
    createdAt: "Sep 24, 2026",
    expectedDelivery: "Sep 29–30, 2026",
    address: "14 Akin Adesola Street, Victoria Island, Lagos",
    timeline: makeTimeline("shipped"),
  },
  {
    id: "JLF-240915-02",
    items: [
      {
        productId: products[5].id,
        productName: products[5].name,
        image: products[5].image,
        quantity: 1,
        unitPrice: products[5].price,
        size: "M",
        color: "Stone",
      },
    ],
    total: 118000,
    paid: 39333,
    remaining: 78667,
    paymentMethod: "installment",
    status: "payment-verification",
    createdAt: "Sep 15, 2026",
    expectedDelivery: "After final payment",
    address: "14 Akin Adesola Street, Victoria Island, Lagos",
    timeline: makeTimeline("payment-verification"),
  },
];

export const wishlistIds = new Set(["studio-leather-tote", "muse-fragrance"]);